const Filter = require('../Models/Filter');

exports.addFilter = async (req, res, next)=>{
    try{

        const data = await Filter({
            home_division:[
                "Dhaka",
                "Chittagong",
                "Sylhet",
                "Khulna",
                "Barisal",
                "Rajshahi",
                "Rangpur",
                "Mymensingh"
            ],
            education:[
                "Doctorate / Phd / MPhil",
                "Masters",
                "Bachelors",
                "FCPS / MD",
                "MBBS / BDS",
                "Undergraduate",
                "Diploma",
                "Professional Degree",
                "HSC / A-Label",
                "Others",
            ],
            professional_area:[
                "Accounting & Banking",
                    "Administration & HR",
                    "Advertising & Media",
                    "Agriculture",
                    "Airline & Aviation",
                    "Architecture & Design",
                    "Artists & Animators",
                    "Beauty & Fashion",
                    "Defense",
                    "Education & Training",
                    "Engineering",
                    "IT & Software Engineering",
                    "Legal",
                    "Medical & Healthcare",
                    "Sales & Marketing",
                    "Business & Others",
                    "Not Working",
                                ],
            working_sector:[
                "Private Company",
                "Government / Public Sector",
                "Defense / Civil Services",
                "Business / Self Employed",
               " Not Working",
            ],
            living_country:[
                "Bangladesh",
                "Australia",
                "Canada",
                "China",
                "Cyprus",
                "Denmark",
                "Finland",
                "France",
                "Germany",
                "Greece",
                "India",
                "Indonesia",
                "Ireland",
                "Italy",
                "Japan",
                "Korea",
                "Kuwait",
                "Malaysia",
                "Nepal",
                "Netherlands",
                "New Zealand",
                "Norway",
                "Oman",
                "Pakistan",
                "Qatar",
                "Russia",
                "Saudi Arabia",
                "Singapore",
                "South Africa",
                "Spain",
                "Sri Lanka",
                "Sweden",
                "Switzerland",
                "Thailand",
                "United Arab Emirates",
               " United Kingdom",
                "USA",
                "Other Countries",
            ],
            height:[
                3,
                31,
                32,
                33,
                34,
                36,
                37,
                38,
                39,

                4,
                41,
                42,
                43,
                44,
                46,
                47,
                48,
                49,

                5,
                51,
                52,
                53,
                54,
                56,
                57,
                58,
                59,

                6,
                61,
                62,
                63,
                64,
                66,
                67,
                68,
                69,

                7,
                71,
                72,
                73,
                74,
                76,
                77,
                78,
                79,

                8,
                81,
                82,
                83,
                84,
                86,
                87,
                88,
                89,
            ],
            weight:[
                18,
                19,

                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,

                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,

                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,

                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,

                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,

                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,

                80,
                81,
                82,
                83,
                84,
                85,
                86,
                87,
                88,
                89,

                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                99,

                100,
                101,
                102,
                103,
                104,
                105,
                106,
                107,
                108,
                109,

                110,
                111,
                112,
                113,
                114,
                115,
                116,
                117,
                118,
                119,
                120,
            ]
        })


        const d = await data.save();

        res.send(d);

    }catch(error){
        next(error);
    }
}


exports.getFilter = async (req, res, next)=>{
    try{
        const data = await Filter.find();
        res.send({status:true, data:data[0]});
    }catch(error){
        next(error);
    }
}